[workstations]
wsl_localhost ansible_connection=local

[windows_machines]
windows_host ansible_host=172.17.0.1 ansible_user=YOUR_WINDOWS_USERNAME ansible_password=YOUR_WINDOWS_PASSWORD ansible_connection=winrm ansible_winrm_server_cert_validation=ignore
